### ISSUE TITLE
Kajang 2 KTM Station missing

### ISSUE THREAD

**Issue by enews** [samleong123/ktmb-myrailtime2.0-php#1]
The new KTM Kajang station opened in March 2023 isn't added into the site station list. 
 [RailTravelStation Link](https://railtravelstation.com/ktm-berhad/station-information/central-line/kajang-2-railway-station/)

Not too sure what the station code is.

**Comment by samleong123** [comment]
The new KTM Kajang 2 Station will be added with the new update later since KTM merged MyRailTime inside KITS and all the old backend API is no longer working

**Comment by samleong123** [comment]
New version of this project has been pushed , Kajang 2 is now available 
https://ktmb.samsam123.name.my/schedule.html?stationcode=20402&stationname=Kajang%202
